theme: jekyll-theme-minimal
url: https://robmuth.github.io
baseurl: /BlogTest
locale: en-US
title: Blog
name: Test Blog
timezone: Europe/Berlin
markdown: kramdown
collections:
  category:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Rob"
      
    scope:
      path: ""
      type: category
    values:
      layout: "category"
