theme: jekyll-theme-minimal
url: https://robmuth.github.io
baseurl: /BlogTest
locale: en-US
title: Blog
name: Blog
timezone: Europe/Berlin
markdown: kramdown
defaults:
  -
    scope:
      path: ""
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Rob"
